### PR TITLE
Add R support for Conductor.

### PR DESCRIPTION
**Pull request by charlieeeeeee**

### CODE REVIEW

**Comment by kevin-bates** [comment]
@charlieeeeeee - could you please take a moment and see if the issues #330 and #332 occur in Conductor - if you haven't already?  Thanks.

**Comment by charlieeeeeee** [comment]
@kevin-bates 
Hey Kevin,

For #332, Luciano and I talked about it yesterday, **yes, Conductor encounters the same issue**, Spark Driver cannot find Rscript in path.

For #330, I tried to reproduce with the steps mentioned in the ticket, **I wasn't able to reproduce** it on Conductor. I waited about 20 minutes,

Thanks,
Charlie

**Comment by kevin-bates** [comment]
@charlieeeeeee - thanks for checking these.  Since #332 also applies to you, we need to make sure that @akchinSTC's PR #338 that adds `--conf spark.sparkr.r.command=/opt/anaconda2/lib/R/bin/Rscript` to the `SPARK_OPTS` is applied to the conductor R `kernel.json` file.

**Comment by akchinSTC** [comment]
LGTM, 
FYI, will need to make changes to your kernel.json file to include the fix for the Rscript issue.

**Pull request closed without merging**
