### PR TITLE
Updated PYTHONPATH in kernel.json for locally installed modules

### PR DESCRIPTION
**Pull request by sanjay-saxena**
Issue #193: Update PYTHONPATH in kernel.json for locally installed modules

Python modules that are installed from within a notebook cell using `!pip install --user <module-name>` get installed under `$HOME/.local/lib/python-<ver>/site-packages` folder. For the module to be successfully imported using `import <module-name>` in a notebook cell, `PYTHONPATH` defined in `kernel.json` for Python-specific kernelspecs should be augmented to include the aforementioned path.

### CODE REVIEW

**Comment by kevin-bates** [comment]
LGTM

**Comment by lresende** [comment]
What are you trying to solve here ? If the environment has "native" python, why then only adding the  user specific packages and not the "global packages" as well ? 

Also, how this works when you have both Anaconda + local python with different set of packages ? 

I am inclined to say we "recommend" anaconda, and document the changes for any other way ? 

Thoughts ?

**Comment by sanjay-saxena** [comment]
@lresende -- The problem we are trying to solve is this -- If a python module is installed from a notebook which is tied to a remote Python kernel using  `!pip install --user <module-name>`, then it gets installed under `$HOME/.local/lib/python-2.7/site-packages folder`. Note that the module was installed using the recommended `--user` switch. However, when the module is imported from another cell using `import <module-name>`, then currently we see an `ImportError`.

To address this problem, we thought augmenting `PYTHONPATH` defined in the `kernel.json` files that are used by the remote Python kernels was needed. Please let us know if there is a better way to address this issue.

There is another problem where if the notebook is tied to a local/default Python kernel(represented by `Python 2` in the drop-down in the browser UI), then we need to modify `kernel.json` under `/opt/anaconda2//share/jupyter/kernels/python2/`. @kevin-bates suggested that the site-admins who would be setting up the environment for the notebook authors will be responsible for updating  `/opt/anaconda2//share/jupyter/kernels/python2/kernel.json`.

**Comment by lresende** [comment]
These kernelspecs are examples on how one could customize it to run distributed kernels. As I mentioned I am inclined to suggest users to use Anaconda, as the regular data science packages are already available. The solution then is, to deploy anaconda and make it the default python in all worker nodes that can be running kernels. This is what we do in the ansible helper scripts.

**Comment by kevin-bates** [comment]
I guess I'm confused.  Does the Anaconda configuration support per-user package locations or is it inherently a shared environment?  If the latter how do we support sand-boxing?  If the former, how do you specify a particular package should be placed into the per-user location?

I completely agree that the kernelspecs we provide should be treated as nothing more than examples, but I also believe those examples need to address the multi-tenancy functionality that we advertise and which I don't think we've got completely identified.

**Comment by lresende** [comment]
I did some further investigation and it seems that this is the place where packages installed with --user are located. The issue is that it depends on the version of python you are using anaconda with (e.g. in my machine, it goes to /Users/lresende/.local/lib/python3.6/site-packages/). Then we need to consider which version of python got installed.

**Comment by sanjay-saxena** [comment]
@lresende  -- @kevin-bates and I did talk about the issue with respect to different versions of Python. We felt that the `kernel.json` that we provide is more of template/sample which need to be tweaked based on whichever version of Python or Spark is being used. So, if we clearly document the fact that the administrators should customize `kernel.json` based on the Python version that they are using, then the onus will be on them to update the version number accordingly.

**Pull request closed without merging**
